### PR TITLE
Fix 20: Remove ItemCanBeNull annotation action

### PR DESCRIPTION
**Pull request by zvirja**
Annotation action is already present in latest version of R#. There is no need to duplicate it.

### CODE REVIEW

**Comment by michael-damatov** [comment]
R# 2016.2 still doesn't support async methods where task result is a reference type:
`async Task<string> MethodAsync() => null; // [ItemNotNull] must be suggested`.

Removing the quick action would reduce the functionality.

**Comment by Zvirja** [comment]
Indeed! Missed that.
In this case, should we just reduce functionality of your plugin to support that particular case only? Do you know about other cases that are not covered?

Also, I'd say that position should be exactly the same as it's for the build-in `Item not null` action.

**Comment by Zvirja** [comment]
It was my miss. Actually, R# has this functionality, see demo:
nullabilitydemo

Am I missing something?

**Comment by Zvirja** [comment]
@michael-damatov Any updates on this one? If you don't have time for these discussions - let me know and I'll just close this PR ;-)

**Pull request closed without merging**
